### ISSUE TITLE
Update Issue - 

### ISSUE THREAD

**Issue by Badn1nja** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#12]
When using the Software section of the website there is a persistent error with the below;

Collected errors:
 * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

Workaround: is to use CLI to run "okpg update"

-----
Side Note: Great work with this, way better stability on 5ghz then when using official OpenWRT, anyone who doesn't speak chinese might struggle to get around the menu but you can change language to auto and this translate anything but the 'Chinese only' applications..

Thanks for the great work, I don't think I'll actually need to install anything on this but you may want to know. Otherwise it's perfect, it doesn't make any network noise and the setup is working perfectly, Thanks @yangxu52 !!!!

Sorry for [不会说中文] !

To change language to ENG.. Follow the below but in chinese
![openwrt-language](https://user-images.githubusercontent.com/57497096/212039097-268b9612-b362-4b81-8c87-aa5ef9aa73fd.png)

**Comment by yangxu52** [comment]
Thanks for approving my work !

About the issue,which you propose,I think it not a issue. 
Because: 
firmware was built base on coolsnowwolf's modify openwrt(LEDE). 
But the software repo base on official （or compatible）firmware probably run failure.
so, you should't use it to install any others software package.

Then, I'm a little curious.
In this firmware, except China, a lot of software(aka plugin) is useless.
I want know :beside  'better stability on 5ghz',what else make you choose it?

Finally, I will add 'How to change English' guide.
Thanks!

**Comment by Badn1nja** [comment]
Openwrt was ok, but it only used 2.4Ghz the 5ghz was failing and there was little documentation on this router. I just need this to be a AP but that really should be using modern wifi not 2.4... 

That and this menu is much better looking then OpenWRT! It's much cleaner and it's got so many features that I may never use that's always fun!

**Comment by yangxu52** [comment]
![image](https://user-images.githubusercontent.com/64672399/212450420-c562fa51-4997-4b19-bdb7-81576aee521d.png)
`iwconfig wlan0 txpower 23`
`iwconfig wlan1 txpower 23`

wlan0 = 2.4
wlan1 = 5

23 is transmit power, max 31 is default 
recommend: between 23-27

more transmit power, more signal intensity,
but less Bandwidth and more failure probability
